### PR TITLE
Fix controller reconcile PodGroup status

### LINKED ISSUE #166: controller should reconcile the status of PodGroup
In the latest code, the controller doesn't quite reconcile the status of PodGroup:

- [x] Field `status.Scheduled` not displayed - fixed by #166

    If a PodGroup is created, we'd expect all [status fields](https://github.com/kubernetes-sigs/scheduler-plugins/blob/e7ca5ee3ba91f98af11c176f7fec2e2ab9e9cc0c/pkg/apis/scheduling/v1alpha1/types.go#L155-L174) to display properly. But for now it's only `status.phase`.
    
    ```
    $ k get pg pg1 -o yaml 
    ...
    status:
      phase: pending
    ```

- [ ] `status.phase` not reconciled well

    If a PodGroup doesn't have any associated Pods, it should stay in `Pending` state. However, it sometimes stays in `Running` (or other state). We's expect status to be always reconciled.

/kind bug

### PR DESCRIPTION
**Pull request by lianghao208**
Fix #166 

It will be 3 final state of pod group: Failed, Finished, Pending.

Pending means: 
1. The pod group has been accepted by the system, but scheduler can not allocate enough resources to it.
2. The PodGroup doesn't have any associated Pods or associated Pods scaled down to 0.

Failed means: 
at least one of `spec.minMember` pods is failed.

Finished means:
all of `spec.minMember` pods are successfully.

/cc @Huang-Wei @cwdsuzhou @denkensk

### CODE REVIEW

File: pkg/controller/podgroup.go [hunk 1]
```diff
@@ -238,6 +238,9 @@ func (ctrl *PodGroupController) syncHandler(key string) error {
 					failed++
 				}
 			}
+		} else {
+			pgCopy.Status.Phase = schedv1alpha1.PodGroupPending
+			break
 		}
 		pgCopy.Status.Failed = failed
```
Comment (denkensk) [inline pkg/controller/podgroup.go:245]: If the number of pods of the group is scaled to 0, we also need to update this information.
```go
pgCopy.Status.Failed = failed
pgCopy.Status.Succeeded = succeeded
pgCopy.Status.Running = running
```

File: pkg/controller/podgroup_test.go [hunk 2]
```diff
@@ -144,6 +153,13 @@ func Test_Run(t *testing.T) {
 
 			pgInformerFactory.Start(ctx.Done())
 			informerFactory.Start(ctx.Done())
+			// pod number scales down to 0
```
Comment (denkensk) [inline pkg/controller/podgroup_test.go:156]: We don't need to add this delete operation here. In this case, we can set 
```go
podNames: []string{}
```
Add this in line 143 or line 144
```go
if len(c.podsNames) != 0 { ... }
```

File: pkg/controller/podgroup_test.go [hunk 3]
```diff
@@ -128,6 +128,15 @@ func Test_Run(t *testing.T) {
 			previousPhase:     v1alpha1.PodGroupPending,
 			desiredGroupPhase: v1alpha1.PodGroupPreScheduling,
 		},
+		{
+			name:              "Pod number scale down to 0",
```
Comment (denkensk) [inline pkg/controller/podgroup_test.go:132]: Group status convert from running to pending ?

**Review by denkensk — COMMENTED** [review]
Thank you for your help. Added some comments.
@lianghao208

File: pkg/controller/podgroup_test.go (hunk 3 above)
Comment (lianghao208) [reply pkg/controller/podgroup_test.go:132]: Yes, if the associated Pods is always 0, the PodGroup will stay in Pending phase:
```go
	switch pgCopy.Status.Phase {
	case "":
		pgCopy.Status.Phase = schedv1alpha1.PodGroupPending
	case schedv1alpha1.PodGroupPending:
		if len(pods) >= int(pg.Spec.MinMember) {
			pgCopy.Status.Phase = schedv1alpha1.PodGroupPreScheduling
			fillOccupiedObj(pg, pods[0])
		}
	default:
...
```

I think the only situation that may cause problem is when associated Pods scale down to 0, which means PodGroup will convert Running to Pending.

File: pkg/controller/podgroup_test.go (hunk 2 above)
Comment (lianghao208) [reply pkg/controller/podgroup_test.go:161]: done

File: pkg/controller/podgroup.go (hunk 1 above)
Comment (lianghao208) [reply pkg/controller/podgroup.go:248]: done

File: pkg/controller/podgroup_test.go (hunk 3 above)
Comment (lianghao208) [reply pkg/controller/podgroup_test.go]: done

**Comment by lianghao208** [comment]
@denkensk Thank you for the review, I've updated the changes, PTAL.

File: pkg/controller/podgroup.go [hunk 4]
```diff
@@ -238,6 +238,12 @@ func (ctrl *PodGroupController) syncHandler(key string) error {
 					failed++
 				}
 			}
+		} else {
```
Comment (denkensk) [inline pkg/controller/podgroup.go:241]: It may be a little duplicate of L248-L250. 
I think it would be better to rewrite it like this, WDYT?
```go
	for _, pod := range pods {
		switch pod.Status.Phase {
		case v1.PodRunning:
			running++
		case v1.PodSucceeded:
			succeeded++
		case v1.PodFailed:
			failed++
		}
	}

       pgCopy.Status.Failed = failed
       pgCopy.Status.Succeeded = succeeded
       pgCopy.Status.Running = running

       if len(pods) == 0 {
            pgCopy.Status.Phase = schedv1alpha1.PodGroupPending
            break
       }
```

**Review by denkensk — COMMENTED** [review]
Just a small comment, please take a look.
@lianghao208

File: pkg/controller/podgroup.go (hunk 4 above)
Comment (lianghao208) [reply pkg/controller/podgroup.go:241]: That makes sense to me. Thanks.

Comment (lianghao208) [reply pkg/controller/podgroup.go]: done.

**Comment by denkensk** [comment]
/lgtm
@lianghao208  Thanks for your help

**Comment by denkensk** [comment]
/assign @huang-wei

Pls take a look again
