### PR TITLE
noderesourcetopology: fix handling of non-NUMA-affine resources

### LINKED ISSUE #355: using k8s extended resources makes the pod unschedulable at noderesourcetopology filtering
The logic in the nrt filter.go resMatchNUMANodes function considers kubernetes extended resources as if they would all have some numa relevance. Since some of the extended resources may not be part of the createNUMANodeList results at all in case they are not registered device plugin resources, the end result is that any (not-best-effort) pod which uses such extended resources, will be considered as unschedulable by nrt.

It would make sense that if the check for numa resources shows that the extended resource isn't numa-related (map returns not-ok), then that resource would be considered to be ok for any numa.

Kubernetes extended resource creation with curl is described here: https://kubernetes.io/docs/tasks/administer-cluster/extended-resource-node/ and the extended resource can then be used in the pod spec resource limits and requests.

A unit test which fails on the issue can be found here: https://github.com/uniemimu/scheduler-plugins/commit/42cb4264dfc8aa9710385fb76223aefd868176c1

### PR DESCRIPTION
**Pull request by fromanirh**
#### What type of PR is this?
/kind bug

#### What this PR does / why we need it:
Review and reorganize how we handle non-NUMA-affine resources, aka resource which don't declare NUMA affinity, like old device plugins and extended resources.

#### Which issue(s) this PR fixes:
Fixes #355 

#### Special notes for your reviewer:
please do not squash commits! I'm using unit tests written by another community member, and we need to preserve their authorship.

### CODE REVIEW

File: pkg/noderesourcetopology/filter.go [hunk 1]
```diff
@@ -68,28 +68,49 @@ func resourcesAvailableInAnyNUMANodes(logKey string, numaNodes NUMANodeList, res
 
 	// Node() != nil already verified in Filter(), which is the only public entry point
 	nodeName := nodeInfo.Node().Name
+	nodeResources := util.ResourceList(nodeInfo.Allocatable)
 
 	for resource, quantity := range resources {
+		if quantity.IsZero() {
+			// why bother? everything's fine from the perspective of this resource
```
Comment (fromanirh) [inline pkg/noderesourcetopology/filter.go:75]: this shouldn't happen, let's `klog.V(4)` something here

File: pkg/noderesourcetopology/filter.go [hunk 2]
```diff
@@ -68,28 +68,49 @@ func resourcesAvailableInAnyNUMANodes(logKey string, numaNodes NUMANodeList, res
...
+			continue
+		}
+
+		// do we have this resource at node level, and if so, do we have enough to met the requirement?
+		isNodeResource := false
+		if nodeQuantity, ok := nodeResources[resource]; ok && nodeQuantity.Cmp(quantity) >= 0 {
```
Comment (fromanirh) [inline pkg/noderesourcetopology/filter.go:81]: this also deserves a `klog.V(6)`

**Comment by fromanirh** [comment]
there are many small cleanups embedded here. I think is better to carefully review them in isolation, so I spawned off https://github.com/kubernetes-sigs/scheduler-plugins/pull/373 from this PR.

File: pkg/noderesourcetopology/filter.go [hunk 3]
```diff
@@ -68,28 +68,51 @@ func resourcesAvailableInAnyNUMANodes(logKey string, numaNodes NUMANodeList, res
 
 	// Node() != nil already verified in Filter(), which is the only public entry point
 	nodeName := nodeInfo.Node().Name
+	nodeResources := util.ResourceList(nodeInfo.Allocatable)
 
 	for resource, quantity := range resources {
+		if quantity.IsZero() {
```
Comment (Tal-or) [inline pkg/noderesourcetopology/filter.go:74]: How a resource request can be zero in the first place?
I don't see why this check is necessary.

File: pkg/noderesourcetopology/filter.go [hunk 4]
```diff
@@ -68,28 +68,51 @@ func resourcesAvailableInAnyNUMANodes(logKey string, numaNodes NUMANodeList, res
...
+			// why bother? everything's fine from the perspective of this resource
+			klog.V(4).InfoS("ignoring zero-qty resource request", "logKey", logKey, "node", nodeName, "resource", resource)
+			continue
+		}
+
+		// do we have this resource at node level, and if so, do we have enough to met the requirement?
+		isNodeResource := false
+		if nodeQuantity, ok := nodeResources[resource]; ok && nodeQuantity.Cmp(quantity) >= 0 {
```
Comment (Tal-or) [inline pkg/noderesourcetopology/filter.go:82]: If ```!ok``` i.e. ```isNodeResource == false``` we should bailout, because if we can't find it at the node level, then a fortiori we can't find it at the NUMA level.

File: pkg/noderesourcetopology/filter.go (hunk 3 above)
Comment (fromanirh) [reply pkg/noderesourcetopology/filter.go:74]: this check was present in the original code and just moved around. We can probably remove it entirely if we deem it unnecessary.

File: pkg/noderesourcetopology/filter.go (hunk 4 above)
Comment (fromanirh) [reply pkg/noderesourcetopology/filter.go:82]: we can have resources only at node level though, like extended resources (https://github.com/kubernetes-sigs/scheduler-plugins/issues/355) or device plugins which don't report NUMA affinity

Comment (Tal-or) [reply pkg/noderesourcetopology/filter.go:82]: I know that it might not be at NUMA level, only at the node level.
But What I'm saying is, if you don't even have it at the **node** level, you can call ```continue``` here.

Comment (fromanirh) [reply pkg/noderesourcetopology/filter.go:82]: right, I misread initially. That's true indeed, we can simplify the flow here.

**Comment by fromanirh** [comment]
depends on https://github.com/kubernetes-sigs/scheduler-plugins/pull/373
please let's *not* squash commits in this PR because I cherry-picked the testcase added to #355 and we should keep proper author attribution (cc @Huang-Wei )

File: pkg/noderesourcetopology/filter.go (hunk 3 above)
Comment (fromanirh) [reply pkg/noderesourcetopology/filter.go:74]: still TBD. I'm not completely sure we want to remove this, event though it should not happen

**Comment by fromanirh** [comment]
still on hold: need to check the test coverage. Everything else should be OK now.

**Comment by fromanirh** [comment]
/hold cancel
I'm now happy enough with the test coverage
